{% set cupti_version= "11.8.0" %}

package:
  name: cupti
  version: {{ cupti_version }}

# TODO
# skip everything except linux-64? what platforms currently have cupti (only linux-64) and what recipes need it?

source:
  url: https://developer.download.nvidia.com/compute/cuda/{{ cupti_version }}/local_installers/{{ runfile_name }}
  sha256: 9223c4af3aebe4a7bbed9abd9b163b03a1b34b855fbc2b4a0d1b706ac09a5a16 
build:
  number: 0

requirements:
  run:
    # from https://docs.nvidia.com/cupti/r_main.html#r_compatibility_requirements
    cudatoolkit >={{ cupti_version }}

test:
  commands:
    - test -f ${PREFIX}/lib/libcupti.so
    - test -f ${PREFIX}/lib/libcupti.so.{{ '.'.join(cupti_version.split('.')[0:2]) }}

# CUDA Profiling Tools Interface (CUPTI) Library
about:
  home: https://developer.nvidia.com/cuda-toolkit
  license: proprietary - Nvidia
  license_family: Proprietary
  summary: development environment for GPU-accelerated applications, CUPTI components
  description: |
    The NVIDIA CUDA Toolkit provides a comprehensive development environment
    for C and C++ developers building GPU-accelerated applications. The CUDA
    Toolkit ncludes a compiler for NVIDIA GPUs, math libraries, and tools for
    debugging and optimizing the performance of your applications.
  doc_url: http://docs.nvidia.com/cuda/#axzz42Eea7t1I
